// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openxc.proto

package com.openxc;

public final class BinaryMessages {
  private BinaryMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VehicleMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .openxc.VehicleMessage.Type type = 1;
    /**
     * <code>optional .openxc.VehicleMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .openxc.VehicleMessage.Type type = 1;</code>
     */
    com.openxc.BinaryMessages.VehicleMessage.Type getType();

    // optional .openxc.RawMessage raw_message = 2;
    /**
     * <code>optional .openxc.RawMessage raw_message = 2;</code>
     */
    boolean hasRawMessage();
    /**
     * <code>optional .openxc.RawMessage raw_message = 2;</code>
     */
    com.openxc.BinaryMessages.RawMessage getRawMessage();
    /**
     * <code>optional .openxc.RawMessage raw_message = 2;</code>
     */
    com.openxc.BinaryMessages.RawMessageOrBuilder getRawMessageOrBuilder();

    // optional .openxc.TranslatedMessage translated_message = 3;
    /**
     * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
     */
    boolean hasTranslatedMessage();
    /**
     * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
     */
    com.openxc.BinaryMessages.TranslatedMessage getTranslatedMessage();
    /**
     * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
     */
    com.openxc.BinaryMessages.TranslatedMessageOrBuilder getTranslatedMessageOrBuilder();
  }
  /**
   * Protobuf type {@code openxc.VehicleMessage}
   */
  public static final class VehicleMessage extends
      com.google.protobuf.GeneratedMessage
      implements VehicleMessageOrBuilder {
    // Use VehicleMessage.newBuilder() to construct.
    private VehicleMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VehicleMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VehicleMessage defaultInstance;
    public static VehicleMessage getDefaultInstance() {
      return defaultInstance;
    }

    public VehicleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VehicleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.openxc.BinaryMessages.VehicleMessage.Type value = com.openxc.BinaryMessages.VehicleMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.openxc.BinaryMessages.RawMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = rawMessage_.toBuilder();
              }
              rawMessage_ = input.readMessage(com.openxc.BinaryMessages.RawMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rawMessage_);
                rawMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.openxc.BinaryMessages.TranslatedMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = translatedMessage_.toBuilder();
              }
              translatedMessage_ = input.readMessage(com.openxc.BinaryMessages.TranslatedMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(translatedMessage_);
                translatedMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.openxc.BinaryMessages.internal_static_openxc_VehicleMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.openxc.BinaryMessages.internal_static_openxc_VehicleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.openxc.BinaryMessages.VehicleMessage.class, com.openxc.BinaryMessages.VehicleMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<VehicleMessage> PARSER =
        new com.google.protobuf.AbstractParser<VehicleMessage>() {
      public VehicleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehicleMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VehicleMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code openxc.VehicleMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RAW = 1;</code>
       */
      RAW(0, 1),
      /**
       * <code>TRANSLATED = 2;</code>
       */
      TRANSLATED(1, 2),
      ;

      /**
       * <code>RAW = 1;</code>
       */
      public static final int RAW_VALUE = 1;
      /**
       * <code>TRANSLATED = 2;</code>
       */
      public static final int TRANSLATED_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return RAW;
          case 2: return TRANSLATED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.openxc.BinaryMessages.VehicleMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:openxc.VehicleMessage.Type)
    }

    private int bitField0_;
    // optional .openxc.VehicleMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.openxc.BinaryMessages.VehicleMessage.Type type_;
    /**
     * <code>optional .openxc.VehicleMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .openxc.VehicleMessage.Type type = 1;</code>
     */
    public com.openxc.BinaryMessages.VehicleMessage.Type getType() {
      return type_;
    }

    // optional .openxc.RawMessage raw_message = 2;
    public static final int RAW_MESSAGE_FIELD_NUMBER = 2;
    private com.openxc.BinaryMessages.RawMessage rawMessage_;
    /**
     * <code>optional .openxc.RawMessage raw_message = 2;</code>
     */
    public boolean hasRawMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .openxc.RawMessage raw_message = 2;</code>
     */
    public com.openxc.BinaryMessages.RawMessage getRawMessage() {
      return rawMessage_;
    }
    /**
     * <code>optional .openxc.RawMessage raw_message = 2;</code>
     */
    public com.openxc.BinaryMessages.RawMessageOrBuilder getRawMessageOrBuilder() {
      return rawMessage_;
    }

    // optional .openxc.TranslatedMessage translated_message = 3;
    public static final int TRANSLATED_MESSAGE_FIELD_NUMBER = 3;
    private com.openxc.BinaryMessages.TranslatedMessage translatedMessage_;
    /**
     * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
     */
    public boolean hasTranslatedMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
     */
    public com.openxc.BinaryMessages.TranslatedMessage getTranslatedMessage() {
      return translatedMessage_;
    }
    /**
     * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
     */
    public com.openxc.BinaryMessages.TranslatedMessageOrBuilder getTranslatedMessageOrBuilder() {
      return translatedMessage_;
    }

    private void initFields() {
      type_ = com.openxc.BinaryMessages.VehicleMessage.Type.RAW;
      rawMessage_ = com.openxc.BinaryMessages.RawMessage.getDefaultInstance();
      translatedMessage_ = com.openxc.BinaryMessages.TranslatedMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, rawMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, translatedMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rawMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, translatedMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.openxc.BinaryMessages.VehicleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.openxc.BinaryMessages.VehicleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.openxc.BinaryMessages.VehicleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code openxc.VehicleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.openxc.BinaryMessages.VehicleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.openxc.BinaryMessages.internal_static_openxc_VehicleMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.openxc.BinaryMessages.internal_static_openxc_VehicleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.openxc.BinaryMessages.VehicleMessage.class, com.openxc.BinaryMessages.VehicleMessage.Builder.class);
      }

      // Construct using com.openxc.BinaryMessages.VehicleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRawMessageFieldBuilder();
          getTranslatedMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.openxc.BinaryMessages.VehicleMessage.Type.RAW;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rawMessageBuilder_ == null) {
          rawMessage_ = com.openxc.BinaryMessages.RawMessage.getDefaultInstance();
        } else {
          rawMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (translatedMessageBuilder_ == null) {
          translatedMessage_ = com.openxc.BinaryMessages.TranslatedMessage.getDefaultInstance();
        } else {
          translatedMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.openxc.BinaryMessages.internal_static_openxc_VehicleMessage_descriptor;
      }

      public com.openxc.BinaryMessages.VehicleMessage getDefaultInstanceForType() {
        return com.openxc.BinaryMessages.VehicleMessage.getDefaultInstance();
      }

      public com.openxc.BinaryMessages.VehicleMessage build() {
        com.openxc.BinaryMessages.VehicleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.openxc.BinaryMessages.VehicleMessage buildPartial() {
        com.openxc.BinaryMessages.VehicleMessage result = new com.openxc.BinaryMessages.VehicleMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (rawMessageBuilder_ == null) {
          result.rawMessage_ = rawMessage_;
        } else {
          result.rawMessage_ = rawMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (translatedMessageBuilder_ == null) {
          result.translatedMessage_ = translatedMessage_;
        } else {
          result.translatedMessage_ = translatedMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.openxc.BinaryMessages.VehicleMessage) {
          return mergeFrom((com.openxc.BinaryMessages.VehicleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.openxc.BinaryMessages.VehicleMessage other) {
        if (other == com.openxc.BinaryMessages.VehicleMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasRawMessage()) {
          mergeRawMessage(other.getRawMessage());
        }
        if (other.hasTranslatedMessage()) {
          mergeTranslatedMessage(other.getTranslatedMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.openxc.BinaryMessages.VehicleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.openxc.BinaryMessages.VehicleMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .openxc.VehicleMessage.Type type = 1;
      private com.openxc.BinaryMessages.VehicleMessage.Type type_ = com.openxc.BinaryMessages.VehicleMessage.Type.RAW;
      /**
       * <code>optional .openxc.VehicleMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .openxc.VehicleMessage.Type type = 1;</code>
       */
      public com.openxc.BinaryMessages.VehicleMessage.Type getType() {
        return type_;
      }
      /**
       * <code>optional .openxc.VehicleMessage.Type type = 1;</code>
       */
      public Builder setType(com.openxc.BinaryMessages.VehicleMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .openxc.VehicleMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.openxc.BinaryMessages.VehicleMessage.Type.RAW;
        onChanged();
        return this;
      }

      // optional .openxc.RawMessage raw_message = 2;
      private com.openxc.BinaryMessages.RawMessage rawMessage_ = com.openxc.BinaryMessages.RawMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.openxc.BinaryMessages.RawMessage, com.openxc.BinaryMessages.RawMessage.Builder, com.openxc.BinaryMessages.RawMessageOrBuilder> rawMessageBuilder_;
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      public boolean hasRawMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      public com.openxc.BinaryMessages.RawMessage getRawMessage() {
        if (rawMessageBuilder_ == null) {
          return rawMessage_;
        } else {
          return rawMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      public Builder setRawMessage(com.openxc.BinaryMessages.RawMessage value) {
        if (rawMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rawMessage_ = value;
          onChanged();
        } else {
          rawMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      public Builder setRawMessage(
          com.openxc.BinaryMessages.RawMessage.Builder builderForValue) {
        if (rawMessageBuilder_ == null) {
          rawMessage_ = builderForValue.build();
          onChanged();
        } else {
          rawMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      public Builder mergeRawMessage(com.openxc.BinaryMessages.RawMessage value) {
        if (rawMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              rawMessage_ != com.openxc.BinaryMessages.RawMessage.getDefaultInstance()) {
            rawMessage_ =
              com.openxc.BinaryMessages.RawMessage.newBuilder(rawMessage_).mergeFrom(value).buildPartial();
          } else {
            rawMessage_ = value;
          }
          onChanged();
        } else {
          rawMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      public Builder clearRawMessage() {
        if (rawMessageBuilder_ == null) {
          rawMessage_ = com.openxc.BinaryMessages.RawMessage.getDefaultInstance();
          onChanged();
        } else {
          rawMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      public com.openxc.BinaryMessages.RawMessage.Builder getRawMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRawMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      public com.openxc.BinaryMessages.RawMessageOrBuilder getRawMessageOrBuilder() {
        if (rawMessageBuilder_ != null) {
          return rawMessageBuilder_.getMessageOrBuilder();
        } else {
          return rawMessage_;
        }
      }
      /**
       * <code>optional .openxc.RawMessage raw_message = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.openxc.BinaryMessages.RawMessage, com.openxc.BinaryMessages.RawMessage.Builder, com.openxc.BinaryMessages.RawMessageOrBuilder> 
          getRawMessageFieldBuilder() {
        if (rawMessageBuilder_ == null) {
          rawMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.openxc.BinaryMessages.RawMessage, com.openxc.BinaryMessages.RawMessage.Builder, com.openxc.BinaryMessages.RawMessageOrBuilder>(
                  rawMessage_,
                  getParentForChildren(),
                  isClean());
          rawMessage_ = null;
        }
        return rawMessageBuilder_;
      }

      // optional .openxc.TranslatedMessage translated_message = 3;
      private com.openxc.BinaryMessages.TranslatedMessage translatedMessage_ = com.openxc.BinaryMessages.TranslatedMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.openxc.BinaryMessages.TranslatedMessage, com.openxc.BinaryMessages.TranslatedMessage.Builder, com.openxc.BinaryMessages.TranslatedMessageOrBuilder> translatedMessageBuilder_;
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      public boolean hasTranslatedMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      public com.openxc.BinaryMessages.TranslatedMessage getTranslatedMessage() {
        if (translatedMessageBuilder_ == null) {
          return translatedMessage_;
        } else {
          return translatedMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      public Builder setTranslatedMessage(com.openxc.BinaryMessages.TranslatedMessage value) {
        if (translatedMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          translatedMessage_ = value;
          onChanged();
        } else {
          translatedMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      public Builder setTranslatedMessage(
          com.openxc.BinaryMessages.TranslatedMessage.Builder builderForValue) {
        if (translatedMessageBuilder_ == null) {
          translatedMessage_ = builderForValue.build();
          onChanged();
        } else {
          translatedMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      public Builder mergeTranslatedMessage(com.openxc.BinaryMessages.TranslatedMessage value) {
        if (translatedMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              translatedMessage_ != com.openxc.BinaryMessages.TranslatedMessage.getDefaultInstance()) {
            translatedMessage_ =
              com.openxc.BinaryMessages.TranslatedMessage.newBuilder(translatedMessage_).mergeFrom(value).buildPartial();
          } else {
            translatedMessage_ = value;
          }
          onChanged();
        } else {
          translatedMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      public Builder clearTranslatedMessage() {
        if (translatedMessageBuilder_ == null) {
          translatedMessage_ = com.openxc.BinaryMessages.TranslatedMessage.getDefaultInstance();
          onChanged();
        } else {
          translatedMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      public com.openxc.BinaryMessages.TranslatedMessage.Builder getTranslatedMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTranslatedMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      public com.openxc.BinaryMessages.TranslatedMessageOrBuilder getTranslatedMessageOrBuilder() {
        if (translatedMessageBuilder_ != null) {
          return translatedMessageBuilder_.getMessageOrBuilder();
        } else {
          return translatedMessage_;
        }
      }
      /**
       * <code>optional .openxc.TranslatedMessage translated_message = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.openxc.BinaryMessages.TranslatedMessage, com.openxc.BinaryMessages.TranslatedMessage.Builder, com.openxc.BinaryMessages.TranslatedMessageOrBuilder> 
          getTranslatedMessageFieldBuilder() {
        if (translatedMessageBuilder_ == null) {
          translatedMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.openxc.BinaryMessages.TranslatedMessage, com.openxc.BinaryMessages.TranslatedMessage.Builder, com.openxc.BinaryMessages.TranslatedMessageOrBuilder>(
                  translatedMessage_,
                  getParentForChildren(),
                  isClean());
          translatedMessage_ = null;
        }
        return translatedMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:openxc.VehicleMessage)
    }

    static {
      defaultInstance = new VehicleMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:openxc.VehicleMessage)
  }

  public interface RawMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 bus = 1;
    /**
     * <code>optional int32 bus = 1;</code>
     */
    boolean hasBus();
    /**
     * <code>optional int32 bus = 1;</code>
     */
    int getBus();

    // optional uint32 message_id = 2;
    /**
     * <code>optional uint32 message_id = 2;</code>
     */
    boolean hasMessageId();
    /**
     * <code>optional uint32 message_id = 2;</code>
     */
    int getMessageId();

    // optional uint64 data = 3;
    /**
     * <code>optional uint64 data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>optional uint64 data = 3;</code>
     */
    long getData();
  }
  /**
   * Protobuf type {@code openxc.RawMessage}
   */
  public static final class RawMessage extends
      com.google.protobuf.GeneratedMessage
      implements RawMessageOrBuilder {
    // Use RawMessage.newBuilder() to construct.
    private RawMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RawMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RawMessage defaultInstance;
    public static RawMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RawMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RawMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bus_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              messageId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              data_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.openxc.BinaryMessages.internal_static_openxc_RawMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.openxc.BinaryMessages.internal_static_openxc_RawMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.openxc.BinaryMessages.RawMessage.class, com.openxc.BinaryMessages.RawMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RawMessage> PARSER =
        new com.google.protobuf.AbstractParser<RawMessage>() {
      public RawMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RawMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RawMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 bus = 1;
    public static final int BUS_FIELD_NUMBER = 1;
    private int bus_;
    /**
     * <code>optional int32 bus = 1;</code>
     */
    public boolean hasBus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 bus = 1;</code>
     */
    public int getBus() {
      return bus_;
    }

    // optional uint32 message_id = 2;
    public static final int MESSAGE_ID_FIELD_NUMBER = 2;
    private int messageId_;
    /**
     * <code>optional uint32 message_id = 2;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 message_id = 2;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    // optional uint64 data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private long data_;
    /**
     * <code>optional uint64 data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 data = 3;</code>
     */
    public long getData() {
      return data_;
    }

    private void initFields() {
      bus_ = 0;
      messageId_ = 0;
      data_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, bus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, messageId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, messageId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.openxc.BinaryMessages.RawMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.openxc.BinaryMessages.RawMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.RawMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.openxc.BinaryMessages.RawMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.RawMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.openxc.BinaryMessages.RawMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.RawMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.openxc.BinaryMessages.RawMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.RawMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.openxc.BinaryMessages.RawMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.openxc.BinaryMessages.RawMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code openxc.RawMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.openxc.BinaryMessages.RawMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.openxc.BinaryMessages.internal_static_openxc_RawMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.openxc.BinaryMessages.internal_static_openxc_RawMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.openxc.BinaryMessages.RawMessage.class, com.openxc.BinaryMessages.RawMessage.Builder.class);
      }

      // Construct using com.openxc.BinaryMessages.RawMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.openxc.BinaryMessages.internal_static_openxc_RawMessage_descriptor;
      }

      public com.openxc.BinaryMessages.RawMessage getDefaultInstanceForType() {
        return com.openxc.BinaryMessages.RawMessage.getDefaultInstance();
      }

      public com.openxc.BinaryMessages.RawMessage build() {
        com.openxc.BinaryMessages.RawMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.openxc.BinaryMessages.RawMessage buildPartial() {
        com.openxc.BinaryMessages.RawMessage result = new com.openxc.BinaryMessages.RawMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bus_ = bus_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.openxc.BinaryMessages.RawMessage) {
          return mergeFrom((com.openxc.BinaryMessages.RawMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.openxc.BinaryMessages.RawMessage other) {
        if (other == com.openxc.BinaryMessages.RawMessage.getDefaultInstance()) return this;
        if (other.hasBus()) {
          setBus(other.getBus());
        }
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.openxc.BinaryMessages.RawMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.openxc.BinaryMessages.RawMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 bus = 1;
      private int bus_ ;
      /**
       * <code>optional int32 bus = 1;</code>
       */
      public boolean hasBus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 bus = 1;</code>
       */
      public int getBus() {
        return bus_;
      }
      /**
       * <code>optional int32 bus = 1;</code>
       */
      public Builder setBus(int value) {
        bitField0_ |= 0x00000001;
        bus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bus = 1;</code>
       */
      public Builder clearBus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bus_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 message_id = 2;
      private int messageId_ ;
      /**
       * <code>optional uint32 message_id = 2;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 message_id = 2;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>optional uint32 message_id = 2;</code>
       */
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000002;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 message_id = 2;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageId_ = 0;
        onChanged();
        return this;
      }

      // optional uint64 data = 3;
      private long data_ ;
      /**
       * <code>optional uint64 data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 data = 3;</code>
       */
      public long getData() {
        return data_;
      }
      /**
       * <code>optional uint64 data = 3;</code>
       */
      public Builder setData(long value) {
        bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:openxc.RawMessage)
    }

    static {
      defaultInstance = new RawMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:openxc.RawMessage)
  }

  public interface TranslatedMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .openxc.TranslatedMessage.Type type = 1;
    /**
     * <code>optional .openxc.TranslatedMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .openxc.TranslatedMessage.Type type = 1;</code>
     */
    com.openxc.BinaryMessages.TranslatedMessage.Type getType();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string string_value = 3;
    /**
     * <code>optional string string_value = 3;</code>
     */
    boolean hasStringValue();
    /**
     * <code>optional string string_value = 3;</code>
     */
    java.lang.String getStringValue();
    /**
     * <code>optional string string_value = 3;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    // optional double numeric_value = 4;
    /**
     * <code>optional double numeric_value = 4;</code>
     */
    boolean hasNumericValue();
    /**
     * <code>optional double numeric_value = 4;</code>
     */
    double getNumericValue();

    // optional bool boolean_value = 5;
    /**
     * <code>optional bool boolean_value = 5;</code>
     */
    boolean hasBooleanValue();
    /**
     * <code>optional bool boolean_value = 5;</code>
     */
    boolean getBooleanValue();

    // optional string string_event = 6;
    /**
     * <code>optional string string_event = 6;</code>
     */
    boolean hasStringEvent();
    /**
     * <code>optional string string_event = 6;</code>
     */
    java.lang.String getStringEvent();
    /**
     * <code>optional string string_event = 6;</code>
     */
    com.google.protobuf.ByteString
        getStringEventBytes();

    // optional double numeric_event = 7;
    /**
     * <code>optional double numeric_event = 7;</code>
     */
    boolean hasNumericEvent();
    /**
     * <code>optional double numeric_event = 7;</code>
     */
    double getNumericEvent();

    // optional bool boolean_event = 8;
    /**
     * <code>optional bool boolean_event = 8;</code>
     */
    boolean hasBooleanEvent();
    /**
     * <code>optional bool boolean_event = 8;</code>
     */
    boolean getBooleanEvent();
  }
  /**
   * Protobuf type {@code openxc.TranslatedMessage}
   */
  public static final class TranslatedMessage extends
      com.google.protobuf.GeneratedMessage
      implements TranslatedMessageOrBuilder {
    // Use TranslatedMessage.newBuilder() to construct.
    private TranslatedMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TranslatedMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TranslatedMessage defaultInstance;
    public static TranslatedMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TranslatedMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TranslatedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.openxc.BinaryMessages.TranslatedMessage.Type value = com.openxc.BinaryMessages.TranslatedMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              stringValue_ = input.readBytes();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              numericValue_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              booleanValue_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              stringEvent_ = input.readBytes();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              numericEvent_ = input.readDouble();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              booleanEvent_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.openxc.BinaryMessages.internal_static_openxc_TranslatedMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.openxc.BinaryMessages.internal_static_openxc_TranslatedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.openxc.BinaryMessages.TranslatedMessage.class, com.openxc.BinaryMessages.TranslatedMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TranslatedMessage> PARSER =
        new com.google.protobuf.AbstractParser<TranslatedMessage>() {
      public TranslatedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TranslatedMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TranslatedMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code openxc.TranslatedMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STRING = 1;</code>
       */
      STRING(0, 1),
      /**
       * <code>NUM = 2;</code>
       */
      NUM(1, 2),
      /**
       * <code>BOOL = 3;</code>
       */
      BOOL(2, 3),
      /**
       * <code>EVENTED_STRING = 4;</code>
       */
      EVENTED_STRING(3, 4),
      /**
       * <code>EVENTED_NUM = 5;</code>
       */
      EVENTED_NUM(4, 5),
      /**
       * <code>EVENTED_BOOL = 6;</code>
       */
      EVENTED_BOOL(5, 6),
      ;

      /**
       * <code>STRING = 1;</code>
       */
      public static final int STRING_VALUE = 1;
      /**
       * <code>NUM = 2;</code>
       */
      public static final int NUM_VALUE = 2;
      /**
       * <code>BOOL = 3;</code>
       */
      public static final int BOOL_VALUE = 3;
      /**
       * <code>EVENTED_STRING = 4;</code>
       */
      public static final int EVENTED_STRING_VALUE = 4;
      /**
       * <code>EVENTED_NUM = 5;</code>
       */
      public static final int EVENTED_NUM_VALUE = 5;
      /**
       * <code>EVENTED_BOOL = 6;</code>
       */
      public static final int EVENTED_BOOL_VALUE = 6;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return STRING;
          case 2: return NUM;
          case 3: return BOOL;
          case 4: return EVENTED_STRING;
          case 5: return EVENTED_NUM;
          case 6: return EVENTED_BOOL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.openxc.BinaryMessages.TranslatedMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:openxc.TranslatedMessage.Type)
    }

    private int bitField0_;
    // optional .openxc.TranslatedMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.openxc.BinaryMessages.TranslatedMessage.Type type_;
    /**
     * <code>optional .openxc.TranslatedMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .openxc.TranslatedMessage.Type type = 1;</code>
     */
    public com.openxc.BinaryMessages.TranslatedMessage.Type getType() {
      return type_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string string_value = 3;
    public static final int STRING_VALUE_FIELD_NUMBER = 3;
    private java.lang.Object stringValue_;
    /**
     * <code>optional string string_value = 3;</code>
     */
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string string_value = 3;</code>
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string string_value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double numeric_value = 4;
    public static final int NUMERIC_VALUE_FIELD_NUMBER = 4;
    private double numericValue_;
    /**
     * <code>optional double numeric_value = 4;</code>
     */
    public boolean hasNumericValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double numeric_value = 4;</code>
     */
    public double getNumericValue() {
      return numericValue_;
    }

    // optional bool boolean_value = 5;
    public static final int BOOLEAN_VALUE_FIELD_NUMBER = 5;
    private boolean booleanValue_;
    /**
     * <code>optional bool boolean_value = 5;</code>
     */
    public boolean hasBooleanValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool boolean_value = 5;</code>
     */
    public boolean getBooleanValue() {
      return booleanValue_;
    }

    // optional string string_event = 6;
    public static final int STRING_EVENT_FIELD_NUMBER = 6;
    private java.lang.Object stringEvent_;
    /**
     * <code>optional string string_event = 6;</code>
     */
    public boolean hasStringEvent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string string_event = 6;</code>
     */
    public java.lang.String getStringEvent() {
      java.lang.Object ref = stringEvent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringEvent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string string_event = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStringEventBytes() {
      java.lang.Object ref = stringEvent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringEvent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double numeric_event = 7;
    public static final int NUMERIC_EVENT_FIELD_NUMBER = 7;
    private double numericEvent_;
    /**
     * <code>optional double numeric_event = 7;</code>
     */
    public boolean hasNumericEvent() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double numeric_event = 7;</code>
     */
    public double getNumericEvent() {
      return numericEvent_;
    }

    // optional bool boolean_event = 8;
    public static final int BOOLEAN_EVENT_FIELD_NUMBER = 8;
    private boolean booleanEvent_;
    /**
     * <code>optional bool boolean_event = 8;</code>
     */
    public boolean hasBooleanEvent() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool boolean_event = 8;</code>
     */
    public boolean getBooleanEvent() {
      return booleanEvent_;
    }

    private void initFields() {
      type_ = com.openxc.BinaryMessages.TranslatedMessage.Type.STRING;
      name_ = "";
      stringValue_ = "";
      numericValue_ = 0D;
      booleanValue_ = false;
      stringEvent_ = "";
      numericEvent_ = 0D;
      booleanEvent_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, numericValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, booleanValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStringEventBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, numericEvent_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, booleanEvent_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, numericValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, booleanValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStringEventBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, numericEvent_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, booleanEvent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.openxc.BinaryMessages.TranslatedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.openxc.BinaryMessages.TranslatedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.openxc.BinaryMessages.TranslatedMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code openxc.TranslatedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.openxc.BinaryMessages.TranslatedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.openxc.BinaryMessages.internal_static_openxc_TranslatedMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.openxc.BinaryMessages.internal_static_openxc_TranslatedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.openxc.BinaryMessages.TranslatedMessage.class, com.openxc.BinaryMessages.TranslatedMessage.Builder.class);
      }

      // Construct using com.openxc.BinaryMessages.TranslatedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.openxc.BinaryMessages.TranslatedMessage.Type.STRING;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        numericValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        booleanValue_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        stringEvent_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        numericEvent_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        booleanEvent_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.openxc.BinaryMessages.internal_static_openxc_TranslatedMessage_descriptor;
      }

      public com.openxc.BinaryMessages.TranslatedMessage getDefaultInstanceForType() {
        return com.openxc.BinaryMessages.TranslatedMessage.getDefaultInstance();
      }

      public com.openxc.BinaryMessages.TranslatedMessage build() {
        com.openxc.BinaryMessages.TranslatedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.openxc.BinaryMessages.TranslatedMessage buildPartial() {
        com.openxc.BinaryMessages.TranslatedMessage result = new com.openxc.BinaryMessages.TranslatedMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stringValue_ = stringValue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.numericValue_ = numericValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.booleanValue_ = booleanValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.stringEvent_ = stringEvent_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.numericEvent_ = numericEvent_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.booleanEvent_ = booleanEvent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.openxc.BinaryMessages.TranslatedMessage) {
          return mergeFrom((com.openxc.BinaryMessages.TranslatedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.openxc.BinaryMessages.TranslatedMessage other) {
        if (other == com.openxc.BinaryMessages.TranslatedMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasStringValue()) {
          bitField0_ |= 0x00000004;
          stringValue_ = other.stringValue_;
          onChanged();
        }
        if (other.hasNumericValue()) {
          setNumericValue(other.getNumericValue());
        }
        if (other.hasBooleanValue()) {
          setBooleanValue(other.getBooleanValue());
        }
        if (other.hasStringEvent()) {
          bitField0_ |= 0x00000020;
          stringEvent_ = other.stringEvent_;
          onChanged();
        }
        if (other.hasNumericEvent()) {
          setNumericEvent(other.getNumericEvent());
        }
        if (other.hasBooleanEvent()) {
          setBooleanEvent(other.getBooleanEvent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.openxc.BinaryMessages.TranslatedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.openxc.BinaryMessages.TranslatedMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .openxc.TranslatedMessage.Type type = 1;
      private com.openxc.BinaryMessages.TranslatedMessage.Type type_ = com.openxc.BinaryMessages.TranslatedMessage.Type.STRING;
      /**
       * <code>optional .openxc.TranslatedMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .openxc.TranslatedMessage.Type type = 1;</code>
       */
      public com.openxc.BinaryMessages.TranslatedMessage.Type getType() {
        return type_;
      }
      /**
       * <code>optional .openxc.TranslatedMessage.Type type = 1;</code>
       */
      public Builder setType(com.openxc.BinaryMessages.TranslatedMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .openxc.TranslatedMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.openxc.BinaryMessages.TranslatedMessage.Type.STRING;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string string_value = 3;
      private java.lang.Object stringValue_ = "";
      /**
       * <code>optional string string_value = 3;</code>
       */
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string string_value = 3;</code>
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string string_value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string string_value = 3;</code>
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_value = 3;</code>
       */
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_value = 3;</code>
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringValue_ = value;
        onChanged();
        return this;
      }

      // optional double numeric_value = 4;
      private double numericValue_ ;
      /**
       * <code>optional double numeric_value = 4;</code>
       */
      public boolean hasNumericValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double numeric_value = 4;</code>
       */
      public double getNumericValue() {
        return numericValue_;
      }
      /**
       * <code>optional double numeric_value = 4;</code>
       */
      public Builder setNumericValue(double value) {
        bitField0_ |= 0x00000008;
        numericValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double numeric_value = 4;</code>
       */
      public Builder clearNumericValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numericValue_ = 0D;
        onChanged();
        return this;
      }

      // optional bool boolean_value = 5;
      private boolean booleanValue_ ;
      /**
       * <code>optional bool boolean_value = 5;</code>
       */
      public boolean hasBooleanValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool boolean_value = 5;</code>
       */
      public boolean getBooleanValue() {
        return booleanValue_;
      }
      /**
       * <code>optional bool boolean_value = 5;</code>
       */
      public Builder setBooleanValue(boolean value) {
        bitField0_ |= 0x00000010;
        booleanValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolean_value = 5;</code>
       */
      public Builder clearBooleanValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        booleanValue_ = false;
        onChanged();
        return this;
      }

      // optional string string_event = 6;
      private java.lang.Object stringEvent_ = "";
      /**
       * <code>optional string string_event = 6;</code>
       */
      public boolean hasStringEvent() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string string_event = 6;</code>
       */
      public java.lang.String getStringEvent() {
        java.lang.Object ref = stringEvent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stringEvent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string string_event = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStringEventBytes() {
        java.lang.Object ref = stringEvent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringEvent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string string_event = 6;</code>
       */
      public Builder setStringEvent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stringEvent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_event = 6;</code>
       */
      public Builder clearStringEvent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        stringEvent_ = getDefaultInstance().getStringEvent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_event = 6;</code>
       */
      public Builder setStringEventBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stringEvent_ = value;
        onChanged();
        return this;
      }

      // optional double numeric_event = 7;
      private double numericEvent_ ;
      /**
       * <code>optional double numeric_event = 7;</code>
       */
      public boolean hasNumericEvent() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double numeric_event = 7;</code>
       */
      public double getNumericEvent() {
        return numericEvent_;
      }
      /**
       * <code>optional double numeric_event = 7;</code>
       */
      public Builder setNumericEvent(double value) {
        bitField0_ |= 0x00000040;
        numericEvent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double numeric_event = 7;</code>
       */
      public Builder clearNumericEvent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        numericEvent_ = 0D;
        onChanged();
        return this;
      }

      // optional bool boolean_event = 8;
      private boolean booleanEvent_ ;
      /**
       * <code>optional bool boolean_event = 8;</code>
       */
      public boolean hasBooleanEvent() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool boolean_event = 8;</code>
       */
      public boolean getBooleanEvent() {
        return booleanEvent_;
      }
      /**
       * <code>optional bool boolean_event = 8;</code>
       */
      public Builder setBooleanEvent(boolean value) {
        bitField0_ |= 0x00000080;
        booleanEvent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolean_event = 8;</code>
       */
      public Builder clearBooleanEvent() {
        bitField0_ = (bitField0_ & ~0x00000080);
        booleanEvent_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:openxc.TranslatedMessage)
    }

    static {
      defaultInstance = new TranslatedMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:openxc.TranslatedMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_openxc_VehicleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_openxc_VehicleMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_openxc_RawMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_openxc_RawMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_openxc_TranslatedMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_openxc_TranslatedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014openxc.proto\022\006openxc\"\274\001\n\016VehicleMessag" +
      "e\022)\n\004type\030\001 \001(\0162\033.openxc.VehicleMessage." +
      "Type\022\'\n\013raw_message\030\002 \001(\0132\022.openxc.RawMe" +
      "ssage\0225\n\022translated_message\030\003 \001(\0132\031.open" +
      "xc.TranslatedMessage\"\037\n\004Type\022\007\n\003RAW\020\001\022\016\n" +
      "\nTRANSLATED\020\002\";\n\nRawMessage\022\013\n\003bus\030\001 \001(\005" +
      "\022\022\n\nmessage_id\030\002 \001(\r\022\014\n\004data\030\003 \001(\004\"\265\002\n\021T" +
      "ranslatedMessage\022,\n\004type\030\001 \001(\0162\036.openxc." +
      "TranslatedMessage.Type\022\014\n\004name\030\002 \001(\t\022\024\n\014" +
      "string_value\030\003 \001(\t\022\025\n\rnumeric_value\030\004 \001(",
      "\001\022\025\n\rboolean_value\030\005 \001(\010\022\024\n\014string_event" +
      "\030\006 \001(\t\022\025\n\rnumeric_event\030\007 \001(\001\022\025\n\rboolean" +
      "_event\030\010 \001(\010\"\\\n\004Type\022\n\n\006STRING\020\001\022\007\n\003NUM\020" +
      "\002\022\010\n\004BOOL\020\003\022\022\n\016EVENTED_STRING\020\004\022\017\n\013EVENT" +
      "ED_NUM\020\005\022\020\n\014EVENTED_BOOL\020\006B\034\n\ncom.openxc" +
      "B\016BinaryMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_openxc_VehicleMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_openxc_VehicleMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_openxc_VehicleMessage_descriptor,
              new java.lang.String[] { "Type", "RawMessage", "TranslatedMessage", });
          internal_static_openxc_RawMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_openxc_RawMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_openxc_RawMessage_descriptor,
              new java.lang.String[] { "Bus", "MessageId", "Data", });
          internal_static_openxc_TranslatedMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_openxc_TranslatedMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_openxc_TranslatedMessage_descriptor,
              new java.lang.String[] { "Type", "Name", "StringValue", "NumericValue", "BooleanValue", "StringEvent", "NumericEvent", "BooleanEvent", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
